name: Aviator 30s Tracker
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'  # ہر گھنٹے میں ایک بار
jobs:
  track-aviator:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # ہر جاب 60 منٹ تک چلے گی
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Continuous Tracker
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: python main.py
