name: Aviator WS Listener

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'  # ہر 10 منٹ بعد

jobs:
  listen-crash:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install websockets

      - name: Run WebSocket listener
        env:
          WS_TOKEN: ${{ secrets.WS_TOKEN }}
        run: python main.py
